server:
  port: 8080

spring:
  application:
    name: captain

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}
      chat-model:
        model-name: gpt-4o
        log-requests: true
        log-responses: true

logging:
  level:
    com.captain: INFO
    org.springframework: INFO
